### ISSUE TITLE
Lograr llamar a builtins en linux

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/exec-to-html#1]
Cambiar en 
```js
if(path.sep==='\\'){
    commandLine='cmd.exe /c '+commandLine.substr(1);
}else{
    commandLine=commandLine.substr(1);
}
```

en el else para que ande el shell. Prefijar con lo que haga falta

**Comment by emilioplatzer** [comment]
Creo que anda

**Comment by diegoefe** [comment]
Sí, anda sin  tocar nada. No lo cerré porque todavía no entiendo bien bien
como para estar seguro
