### ISSUE TITLE
Hacer andar todos los casos de prueba en linux

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/exec-to-html#10]
Faltan los que ahora están salteados con:
```js
skipped:!winOS
```

**Comment by diegoefe** [comment]
Listo. Tener en cuenta que, de igual manera que el 'cp437' en windows, 'utf8' en Linux depende de la configuración del lenguage del OS y el filesystem.

**Comment by emilioplatzer** [comment]
Ok con cp437 y demás configuraciones. En principio queda así sabiéndolo (habría que agrear un notice en el README), cuando necesitemos cambiarlo en los tests, lo cambiamos; si alguna vez alguien pide lo hacemos.
