### ISSUE TITLE
Implementar el pasaje e informe de exit-code

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/exec-to-html#2]
con la opción exitCode:true hay que informar el número de exit code así:
`{origin:'exit-code', text:9} `  (9 o el número que haya sido el exit code)

Además cuando se ejecute una secuencia de comandos el exitcode hay que informárselo al siguiente

**Comment by emilioplatzer** [comment]
La parte del informe ya la hice. 

Queda poder tomar el exit code. Eso está en fixtures.js, hay que asignar el valor en: 
```js
var recivedExitCode = "issue #2";
```

**Comment by emilioplatzer** [comment]
No estoy seguro de que esto se pueda hacer. O sea en windows dentro de un archivo.bat se puede escribir algo así como

```bat
commando1 parametro2
IF ERRORLEVEL 3 GOTO label3
```

ERRORLEVEL es una especie de directiva que compara el exit code último recibido. Lo que no sé es si eso se puede mirar desde un comando. 

La resolución de esto es condicional.

**Comment by diegoefe** [comment]
No sirve esto:
https://nodejs.org/api/child_process.html#child_process_event_close

**Comment by diegoefe** [comment]
Te mandé un mail que habla de esto
