### ISSUE TITLE
Bufferear caracteres, pero si se recibe datos por otro canal, vaciar (enviando) el buffer

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/exec-to-html#5]
por ejemplo si se están recibiendo partes de una línea por el stdout y todavía no se recibió el EOL y llega un mensaje de error, hay que enviar por el stdout lo que se recibió y empezar a recibir partes del stderr (hasta recibir un EOL o que vuelva a cambiar el canal).

**Comment by diegoefe** [comment]
Te envié un mail con comentarios. La cierro porque está
